/**
 * Layout Component
 *
 * Main layout orchestrator for the application.
 * This component is generated by `hai3 scaffold layout`.
 * Uses @hai3/uikit for UI components.
 */

import React, { useEffect } from 'react';
import { useAppDispatch, apiRegistry, setUser, setHeaderLoading, type HeaderUser } from '@hai3/react';
import { Header } from './Header';
import { Footer } from './Footer';
import { Menu } from './Menu';
import { Sidebar } from './Sidebar';
import { Screen } from './Screen';
import { Popup } from './Popup';
import { Overlay } from './Overlay';
import { ACCOUNTS_DOMAIN, type ApiUser } from './api';

export interface LayoutProps {
  children?: React.ReactNode;
}

/**
 * Convert API user to header user info
 */
function toHeaderUser(user: ApiUser): HeaderUser {
  const displayName = `${user.firstName || ''} ${user.lastName || ''}`.trim();
  return {
    displayName: displayName || undefined,
    email: user.email || undefined,
    avatarUrl: user.avatarUrl,
  };
}

export const Layout: React.FC<LayoutProps> = ({ children }) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    // Bootstrap application on mount - fetch current user
    const fetchUser = async () => {
      try {
        // Check if accounts service is registered before trying to use it
        const hasAccounts = (apiRegistry as { has(domain: string): boolean }).has(ACCOUNTS_DOMAIN);
        if (!hasAccounts) {
          // Accounts service not registered - skip user fetch
          return;
        }

        dispatch(setHeaderLoading(true));
        // Get accounts service
        // Type assertion needed because accounts domain may not be augmented in ApiServicesMap yet
        const accountsService = (apiRegistry as { getService(domain: string): unknown }).getService(ACCOUNTS_DOMAIN) as { getCurrentUser?: () => Promise<{ user: ApiUser }> } | undefined;
        if (accountsService?.getCurrentUser) {
          const response = await accountsService.getCurrentUser();
          if (response?.user) {
            dispatch(setUser(toHeaderUser(response.user)));
          }
        }
      } catch (error) {
        console.warn('Failed to fetch user:', error);
        dispatch(setHeaderLoading(false));
      }
    };

    fetchUser();
  }, [dispatch]);

  return (
    <div className="flex flex-col h-full w-full overflow-hidden">
      {/* Top row: Menu + Header + Content + Sidebar */}
      <div className="flex flex-1 overflow-hidden">
        {/* Menu - full height on left */}
        <Menu />

        {/* Right side: Header + Content */}
        <div className="flex flex-col flex-1 overflow-hidden">
          {/* Header */}
          <Header />

          {/* Main content area */}
          <div className="flex flex-1 overflow-hidden">
            {/* Main content */}
            <Screen>{children}</Screen>

            {/* Sidebar */}
            <Sidebar />
          </div>
        </div>
      </div>

      {/* Footer - full width */}
      <Footer />

      {/* Popups */}
      <Popup />

      {/* Overlay */}
      <Overlay />
    </div>
  );
};

Layout.displayName = 'Layout';
